language: python

virtualenv:
  system_site_packages: true

python:
  - '3.6'

install:
  - sudo pip install -r requirements.txt
  - sudo python setup.py develop
  - sudo pip install tox

script:
  - pip list --format=columns | grep container-service-extension
  - python -c 'import pkg_resources; print(pkg_resources.require("container_service_extension")[0].version)'
  - tox -e flake8
