rabbitmq:
    host: vcd.cpsbu.eng.vmware.com
    port: 5672
    user: '****'
    password: '*****'
    exchange: vcdext
    routing_key: cse

service:
    listeners: 2
    logging_level: 20
    logging_format: '%(levelname) -8s %(asctime)s %(name) -8s %(funcName) -8s %(lineno) -5d: %(message)s'
    key_filename: '~/.ssh/id_rsa_vmw'
    key_filename_pub: '~/.ssh/id_rsa_vmw.pub'
    catalog: mycatalog
    template_master: kube.ova
    template_worker: kube.ova

vcd:
    host: vcd.cpsbu.eng.vmware.com
    port: 443
    username: administrator
    password: '*************'
    api_version: '5.6'
    verify: False
    log: True
