kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c1
  annotations:
    volume.beta.kubernetes.io/storage-class: "vcloud-director"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
